### ISSUE TITLE
Replace FileList with Array/List of File

### ISSUE THREAD

**Issue by the-dr-lazy** [purescript-web/purescript-web-file#7]
The FileList API looks like a legacy API, It's not possible to use `List` or `Array` related functions with it. It doesn't instantiate any class and it doesn't make sense!
There is a [stackoverflow thread](https://stackoverflow.com/a/25333553/11948651) and [spec](https://www.w3.org/TR/FileAPI/#filelist-section) which explains more this topic.
Why not just use `Array File` or `List File`?

**Comment by BebeSparkelSparkel** [comment]
@thebrodmann checkout pr #8 
I thought the same and made a pr. Should do what you want

**Comment by BebeSparkelSparkel** [comment]
@thebrodmann funny you're on the halogen `onFileUpload` too. Looks like we want the same thing

**Comment by hdgarrood** [comment]
Can either of you explain in a bit more detail what prompted this please?

**Comment by garyb** [comment]
To answer the question: these libraries exist to implement the spec in a mostly unopinionated way, so although it may be more convenient to deal with an array, that's not what the API actually is. 🙂
